main/urls.py
from django.urls import path, include
from .views import (
    indexView,
    sverdlovView,
    batkenView,
    create_regionView,
    create_areaView,
    update_regionView,
    delete_regionView,
    update_areaView,
    delete_areaView,

)

app_name = 'main'


urlpatterns = [

    path('index/', indexView, name= 'index'),
    path('sverdlov/<int:pk>/',  sverdlovView, name='sverdlov'),
    path('create_region/', create_regionView, name='create_region'),
    path('batken/<int:pk>/', batkenView, name='batken'),
    path('create_area/', create_areaView, name='create_area'),
    path('update_region/<int:id>/',update_regionView, name='update_region'),
    path('delete_region/<int:id>/',delete_regionView, name='delete_region'),
    path('update_area/<int:id>/',update_areaView, name='update_area'),
    path('delete_area/<int:id>/',delete_areaView, name='delete_area')
]

temlate_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'))
]

main/models.py
from django.db import models

class Regions(models.Model):
    name = models.CharField(max_length=60)
    info = models.TextField()

    def __str__(self):
        return self.name


class Areas(models.Model):
    name = models.CharField(max_length=60)
    info = models.TextField()

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import Regions
from .models import Areas


class CreateRegionForm(forms.ModelForm):
    class Meta:
        model = Regions
        fields = "__all__"


class CreateAreaForm(forms.ModelForm):
    class Meta:
        model = Areas
        fields = "__all__"

main/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Regions, Areas
from .forms import CreateRegionForm
from .forms import CreateAreaForm


def indexView(request):
    regions = Regions.objects.all()
    areas = Areas.objects.all()
    context = {
        'regions': regions,
        'areas': areas
    }
    return render(request, 'main/index.html', context)

def sverdlovView(request, pk):
    regions = Regions.objects.all()
    region = Regions.objects.get(id=pk)
    areas = Areas.objects.all()

    context = {
        'name': region.name,
        'regions': regions,
        'areas': areas,
        'region': region,

    }
    return render(request, 'main/sverdlov.html', context)



def batkenView(request, pk):
    areas = Areas.objects.all()
    area = Areas.objects.get(id=pk)
    regions = Regions.objects.all()
    context = {

        'regions': regions,
        'areas': areas,
        'area': area,
    }

    return render(request, 'main/batken.html', context)

def create_regionView(request):
    if request.method == 'POST':
        form = CreateRegionForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='main:index')
        else:
            return HttpResponse("ERROR")

    form = CreateRegionForm()
    context = {
        'form': form
    }
    return render(request, 'main/create/create.html', context)



def create_areaView(request):

    if request.method == 'POST':
        form = CreateAreaForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='main:index')
        else:
            return HttpResponse("ERROR")

    form = CreateAreaForm()
    context = {
        'form': form
    }
    return render(request, 'main/create/create.html', context)

def update_regionView(request, id):
    region = Regions.objects.get(id=id)
    if request.method == 'POST':
        form = CreateRegionForm(request.POST, instance=region)
        if form.is_valid():
            form.save()
            return redirect(to='main:index')
        return HttpResponse("invalid data")

    form = CreateRegionForm(instance=region)
    context = {'form':form}
    return render(request, 'main/create/create.html', context)

def delete_regionView(request, id):
    region = Regions.objects.get(id=id)
    region.delete()
    return redirect(to='main:index')


def update_areaView(request, id):
    area = Areas.objects.get(id=id)
    if request.method == 'POST':
        form = CreateAreaForm(request.POST, instance=area)
        if form.is_valid():
            form.save()
            return redirect(to='main:index')
        return HttpResponse("invalid data")

    form = CreateAreaForm(instance=area)
    context = {'form':form}
    return render(request, 'main/create/create.html', context)


def delete_areaView(request, id):
    area= Areas.objects.get(id=id)
    area.delete()
    return redirect(to='main:index')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body>


<div class="Header">
    {% block Header %}
    <h1>Header</h1>
    {% endblock Header %}
</div>

<div class="Menu">
    {% block Menu %}
    {% endblock Menu %}
</div>

<div class="Content">
    {% block Content %}
    <h1>Content</h1>
    {% endblock Content %}
</div>

<div class="Footer">
    {% block Footer %}
    <h1>Footer</h1>
    {% endblock Footer %}
</div>

</body>
</html>

templates/main/batken.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>batken</title>
</head>
<body>

</body>
</html>


{% extends "base.html" %}

{% block Content %}

    <h1>{{area.name}}</h1>
    <p>{{area.info}}</p>
<a href="{% url 'main:update_area' area.id %}">
    <button>Update</button>
</a>
<a href="{% url 'main:delete_area' area.id %}">
    <button>Delete</button>
</a>
    {% endblock %}

 {% block Menu %}
    <h1>Menu</h1>
    <div class="navbar">
        <a href="#">Главная</a>
        <a href="#">Новости</a>
        <div class="dropdown">
            <button class="dropbtn"> obs
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="{% url 'main:create_area' %}">oblast кошуу</a>
                {% for area in areas %}
                <a href="{% url 'main:batken' area.id %}">{{area.name}}</a>
                {% endfor %}
            </div>
        </div>
        <div class="dropdown">
            <button class="dropbtn"> Райондор
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="{% url 'main:create_region' %}">Район кошуу</a>
                {% for region in regions %}
                <a href="{% url 'main:sverdlov' region.id %}">{{region.name}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
     {% endblock %}

templates/main/create/create.html
{% extends 'base.html' %}

{% block Content%}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
    <button>Сакта</button>
    </form>

{% endblock %}

templates/main/index.html
{% extends 'base.html' %}

 {% block Menu %}
    <h1>Menu</h1>
    <div class="navbar">
        <a href="#">Главная</a>
        <a href="#">Новости</a>
        <div class="dropdown">
            <button class="dropbtn"> obs
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                 <a href="{% url 'main:create_area' %}">oblast koshuu</a>
                {% for area in areas %}
                <a href="{% url 'main:batken' area.id %}">{{area.name}}</a>
                {% endfor %}
            </div>
        </div>
        <div class="dropdown">
            <button class="dropbtn"> Райондор
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                 <a href="{% url 'main:create_region' %}">Район кошуу</a>
                {% for region in regions %}
                <a href="{% url 'main:sverdlov' region.id %}">{{region.name}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
     {% endblock %}

templates/main/news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>news</title>
</head>
<body>

</body>
</html>

{% extends "base.html" %}
{% block Content %}
NEWS
{% endblock %}

templates/main/sverdlov.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>sverdlov</title>
</head>
<body>

</body>
</html>

{% extends "base.html" %}

{% block Content %}
    <h1>{{region.name}}</h1>
    <p>{{region.info}}</p>
<a href="{% url 'main:update_region' region.id %}">
    <button>Update</button>
</a>
<a href="{% url 'main:delete_region' region.id %}">
    <button>Delete</button>
</a>

{% endblock %}

 {% block Menu %}
    <h1>Menu</h1>
    <div class="navbar">
        <a href="#">Главная</a>
        <a href="#">Новости</a>
        <div class="dropdown">
            <button class="dropbtn"> obs
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                 <a href="{% url 'main:create_area' %}">oblast кошуу</a>
                {% for area in areas %}
                <a href="{% url 'main:batken' area.id %}">{{area.name}}</a>
                {% endfor %}
            </div>
        </div>
        <div class="dropdown">
            <button class="dropbtn"> Райондор
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                 <a href="{% url 'main:create_region' %}">Район кошуу</a>
                {% for region in regions %}
                <a href="{% url 'main:sverdlov' region.id %}">{{region.name}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
     {% endblock %}

templates/main/tema.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>tema</title>
</head>
<body>

</body>
</html>

{% extends "base.html" %}
{% block Content %}
TEMA
{% endblock %}